FROM ghcr.io/astral-sh/uv:0.5.11-python3.13-bookworm-slim

LABEL org.opencontainers.image.authors "Jose Sanchez-Gallego, gallegoj@uw.edu"
LABEL org.opencontainers.image.source https://github.com/sdss/lvmbeat

WORKDIR /app

ENV UV_COMPILE_BYTECODE 1
ENV ENV UV_LINK_MODE copy

# Copy the project into the image
ADD . /app

# Sync the project
RUN uv sync --frozen --no-cache

CMD ["/app/.venv/bin/fastapi", "run", "src/lvmbeat/monitor.py", "--port", "8111", "--host", "0.0.0.0"]
