FROM ghcr.io/astral-sh/uv:0.5.11-python3.13-bookworm-slim

LABEL org.opencontainers.image.authors="Jose Sanchez-Gallego, gallegoj@uw.edu"
LABEL org.opencontainers.image.source=https://github.com/sdss/lvmbeat

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

# Copy the project into the image
ADD . /app

# Sync the project
RUN uv sync --frozen --no-cache

RUN apt-get remove -y build-essential
RUN apt-get autoremove -y

CMD ["/app/.venv/bin/lvmbeat", "actor", "start", "--debug"]
