name: Build actor container

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main

jobs:
  docker-actor:
    name: Build actor container

    runs-on: ubuntu-24.04

    env:
      USER: sdss
      APP: lvmbeat

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ env.USER }}/${{ env.APP }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          provenance: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: containers/Dockerfile-lvmbeat

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
